# Generated by Django 5.0.6 on 2024-07-08 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tarefa_data_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_termino',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
